name: WakaTime Stats Update

on:
  schedule:
    - cron: '0 * * * *' # her saat günceller
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_TIME: true
          SHOW_COMMIT: true

      - name: Commit & Push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Updated WakaTime stats"
          git push
